import React from "react";

export const Trophy = () => {
  return (
    <svg
      className="size-6 md:size-14"
      width="120"
      height="110"
      viewBox="0 0 120 110"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="20"
        y="10"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="50"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="30"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="40"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="70"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="55"
        y="80"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="90"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="60"
        y="90"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="60"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="70"
        y="90"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="70"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="80"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="40"
        y="90"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="40"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="30"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="60"
        y="70"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="60"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="55"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="55"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="55"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="70"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="80"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="50"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="10"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="100"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="110"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect y="30" width="10" height="10" fill="var(--color-primary-300)" />
      <rect
        x="10"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="10"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="100"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect x="80" width="10" height="10" fill="var(--color-primary-300)" />
      <rect x="70" width="10" height="10" fill="var(--color-primary-300)" />
      <rect x="60" width="10" height="10" fill="var(--color-primary-300)" />
      <rect x="50" width="10" height="10" fill="var(--color-primary-300)" />
      <rect x="40" width="10" height="10" fill="var(--color-primary-300)" />
      <rect x="30" width="10" height="10" fill="var(--color-primary-300)" />
    </svg>
  );
};
