import React from "react";

export const User = ({width = 15, height = 15}) => {
  return (
    <svg
      width={`${width}`}
      height={`${height}`}
      viewBox={`0 0 100 110`}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect y="90" width="10" height="10" fill="var(--color-primary-300)" />
      <rect y="80" width="10" height="10" fill="var(--color-primary-300)" />
      <rect
        x="10"
        y="70"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="30"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="40"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="35"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect x="35" width="10" height="10" fill="var(--color-primary-300)" />
      <rect
        x="15"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="75"
        y="20"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="25"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="65"
        y="30"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="25"
        y="10"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="65"
        y="10"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="45"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect x="45" width="10" height="10" fill="var(--color-primary-300)" />
      <rect
        x="55"
        y="40"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect x="55" width="10" height="10" fill="var(--color-primary-300)" />
      <rect
        x="60"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="70"
        y="60"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="80"
        y="70"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="80"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="90"
        y="90"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="80"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="70"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="60"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="50"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="40"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="30"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="20"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
      <rect
        x="10"
        y="100"
        width="10"
        height="10"
        fill="var(--color-primary-300)"
      />
    </svg>
  );
};
