import React from "react";

export const Watch = () => {
  return (
    <svg
      className="size-7 md:size-14"
      width="154"
      height="154"
      viewBox="0 0 154 154"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="14"
        y="28"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="28"
        y="14"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect x="42" width="14" height="14" fill="var(--color-primary-200)" />
      <rect x="56" width="14" height="14" fill="var(--color-primary-200)" />
      <rect x="70" width="14" height="14" fill="var(--color-primary-200)" />
      <rect x="84" width="14" height="14" fill="var(--color-primary-200)" />
      <rect x="98" width="14" height="14" fill="var(--color-primary-200)" />
      <rect
        x="112"
        y="14"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="126"
        y="28"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="140"
        y="42"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="140"
        y="56"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="140"
        y="70"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="140"
        y="84"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="126"
        y="112"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="112"
        y="126"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="98"
        y="140"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="84"
        y="140"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="70"
        y="140"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="56"
        y="140"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="42"
        y="140"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="28"
        y="126"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="14"
        y="112"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect y="98" width="14" height="14" fill="var(--color-primary-200)" />
      <rect y="84" width="14" height="14" fill="var(--color-primary-200)" />
      <rect y="70" width="14" height="14" fill="var(--color-primary-200)" />
      <rect y="56" width="14" height="14" fill="var(--color-primary-200)" />
      <rect y="42" width="14" height="14" fill="var(--color-primary-200)" />
      <rect
        x="70"
        y="60"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="70"
        y="46"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="70"
        y="74"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="84"
        y="88"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="98"
        y="102"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
      <rect
        x="140"
        y="98"
        width="14"
        height="14"
        fill="var(--color-primary-200)"
      />
    </svg>
  );
};
